// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	domain "tinderclone_back/src/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// IUserStore is an autogenerated mock type for the IUserStore type
type IUserStore struct {
	mock.Mock
}

// IsUsernameAlreadyTaken provides a mock function with given fields: username
func (_m *IUserStore) IsUsernameAlreadyTaken(username string) bool {
	ret := _m.Called(username)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SaveUser provides a mock function with given fields: entity
func (_m *IUserStore) SaveUser(entity *domain.User) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectUserByUsername provides a mock function with given fields: username
func (_m *IUserStore) SelectUserByUsername(username string) (*domain.User, error) {
	ret := _m.Called(username)

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIUserStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserStore creates a new instance of IUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserStore(t mockConstructorTestingTNewIUserStore) *IUserStore {
	mock := &IUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
